version: '3'
services:
  meshforms:
    healthcheck:
      test: curl --fail http://127.0.0.1:80/join || exit 1
      interval: 1s
      timeout: 1s
      retries: 3
      start_period: 1s
    networks:
      - ui
    expose:
      - 80
    env_file:
      - .env
    image:
      willnilges/meshforms:main

networks:
  ui:
    external: $COMPOSE_EXTERNAL_NETWORK
    name: $COMPOSE_NETWORK_NAME
