/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The logical node this Device is located within. This node's network_number field corresponds to the static IP address and OSPF ID of this device or the DHCP range it receives an address from. The network number is also usually found in the device name
 * @export
 * @interface AccessPointNode
 */
export interface AccessPointNode {
    /**
     * 
     * @type {string}
     * @memberof AccessPointNode
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof AccessPointNode
     */
    networkNumber?: number | null;
}

/**
 * Check if a given object implements the AccessPointNode interface.
 */
export function instanceOfAccessPointNode(value: object): value is AccessPointNode {
    return true;
}

export function AccessPointNodeFromJSON(json: any): AccessPointNode {
    return AccessPointNodeFromJSONTyped(json, false);
}

export function AccessPointNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessPointNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'networkNumber': json['network_number'] == null ? undefined : json['network_number'],
    };
}

export function AccessPointNodeToJSON(value?: AccessPointNode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'network_number': value['networkNumber'],
    };
}

