/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A reference to a Link object, via one or more of the following keys: ['id']
 * @export
 * @interface AccessPointLinksFromInner
 */
export interface AccessPointLinksFromInner {
    /**
     * 
     * @type {string}
     * @memberof AccessPointLinksFromInner
     */
    id?: string;
}

/**
 * Check if a given object implements the AccessPointLinksFromInner interface.
 */
export function instanceOfAccessPointLinksFromInner(value: object): value is AccessPointLinksFromInner {
    return true;
}

export function AccessPointLinksFromInnerFromJSON(json: any): AccessPointLinksFromInner {
    return AccessPointLinksFromInnerFromJSONTyped(json, false);
}

export function AccessPointLinksFromInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): AccessPointLinksFromInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function AccessPointLinksFromInnerToJSON(value?: AccessPointLinksFromInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

