/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `OSMNominatim` - OSMNominatim
 * * `OSMNominatimZIPOnly` - OSMNominatimZIPOnly
 * * `NYCPlanningLabs` - NYCPlanningLabs
 * * `PeliasStringParsing` - PeliasStringParsing
 * * `ReverseGeocodeFromCoordinates` - ReverseGeocodeFromCoordinates
 * * `HumanEntry` - HumanEntry
 * @export
 */
export const AddressTruthSourcesEnum = {
    OsmNominatim: 'OSMNominatim',
    OsmNominatimZipOnly: 'OSMNominatimZIPOnly',
    NycPlanningLabs: 'NYCPlanningLabs',
    PeliasStringParsing: 'PeliasStringParsing',
    ReverseGeocodeFromCoordinates: 'ReverseGeocodeFromCoordinates',
    HumanEntry: 'HumanEntry'
} as const;
export type AddressTruthSourcesEnum = typeof AddressTruthSourcesEnum[keyof typeof AddressTruthSourcesEnum];


export function instanceOfAddressTruthSourcesEnum(value: any): boolean {
    for (const key in AddressTruthSourcesEnum) {
        if (Object.prototype.hasOwnProperty.call(AddressTruthSourcesEnum, key)) {
            if (AddressTruthSourcesEnum[key as keyof typeof AddressTruthSourcesEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function AddressTruthSourcesEnumFromJSON(json: any): AddressTruthSourcesEnum {
    return AddressTruthSourcesEnumFromJSONTyped(json, false);
}

export function AddressTruthSourcesEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): AddressTruthSourcesEnum {
    return json as AddressTruthSourcesEnum;
}

export function AddressTruthSourcesEnumToJSON(value?: AddressTruthSourcesEnum | null): any {
    return value as any;
}

