/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BuildingNodesInner
 */
export interface BuildingNodesInner {
    /**
     * 
     * @type {string}
     * @memberof BuildingNodesInner
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BuildingNodesInner
     */
    networkNumber?: number | null;
}

/**
 * Check if a given object implements the BuildingNodesInner interface.
 */
export function instanceOfBuildingNodesInner(value: object): value is BuildingNodesInner {
    return true;
}

export function BuildingNodesInnerFromJSON(json: any): BuildingNodesInner {
    return BuildingNodesInnerFromJSONTyped(json, false);
}

export function BuildingNodesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingNodesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'networkNumber': json['network_number'] == null ? undefined : json['network_number'],
    };
}

export function BuildingNodesInnerToJSON(value?: BuildingNodesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'network_number': value['networkNumber'],
    };
}

