/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A reference to a Install object, via one or more of the following keys: ['id', 'install_number']
 * @export
 * @interface BuildingInstallsInner
 */
export interface BuildingInstallsInner {
    /**
     * 
     * @type {string}
     * @memberof BuildingInstallsInner
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BuildingInstallsInner
     */
    installNumber?: number;
}

/**
 * Check if a given object implements the BuildingInstallsInner interface.
 */
export function instanceOfBuildingInstallsInner(value: object): value is BuildingInstallsInner {
    return true;
}

export function BuildingInstallsInnerFromJSON(json: any): BuildingInstallsInner {
    return BuildingInstallsInnerFromJSONTyped(json, false);
}

export function BuildingInstallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingInstallsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'installNumber': json['install_number'] == null ? undefined : json['install_number'],
    };
}

export function BuildingInstallsInnerToJSON(value?: BuildingInstallsInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'install_number': value['installNumber'],
    };
}

