/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The primary node for this Building, for cases where it has more than one. This is the node bearing the network number that the building is collquially referred to by volunteers and is usually the first NN held by any equipment on the building. If present, this must also be included in nodes
 * @export
 * @interface BuildingPrimaryNode
 */
export interface BuildingPrimaryNode {
    /**
     * 
     * @type {string}
     * @memberof BuildingPrimaryNode
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof BuildingPrimaryNode
     */
    networkNumber?: number | null;
}

/**
 * Check if a given object implements the BuildingPrimaryNode interface.
 */
export function instanceOfBuildingPrimaryNode(value: object): value is BuildingPrimaryNode {
    return true;
}

export function BuildingPrimaryNodeFromJSON(json: any): BuildingPrimaryNode {
    return BuildingPrimaryNodeFromJSONTyped(json, false);
}

export function BuildingPrimaryNodeFromJSONTyped(json: any, ignoreDiscriminator: boolean): BuildingPrimaryNode {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'networkNumber': json['network_number'] == null ? undefined : json['network_number'],
    };
}

export function BuildingPrimaryNodeToJSON(value?: BuildingPrimaryNode | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'network_number': value['networkNumber'],
    };
}

