/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CityErrorResponse
 */
export interface CityErrorResponse {
    /**
     * 
     * @type {string}
     * @memberof CityErrorResponse
     */
    detail: string;
}

/**
 * Check if a given object implements the CityErrorResponse interface.
 */
export function instanceOfCityErrorResponse(value: object): value is CityErrorResponse {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function CityErrorResponseFromJSON(json: any): CityErrorResponse {
    return CityErrorResponseFromJSONTyped(json, false);
}

export function CityErrorResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): CityErrorResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function CityErrorResponseToJSON(value?: CityErrorResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detail': value['detail'],
    };
}

