/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ErrorResponseMissingFields
 */
export interface ErrorResponseMissingFields {
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof ErrorResponseMissingFields
     */
    detail: { [key: string]: any; };
}

/**
 * Check if a given object implements the ErrorResponseMissingFields interface.
 */
export function instanceOfErrorResponseMissingFields(value: object): value is ErrorResponseMissingFields {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    return true;
}

export function ErrorResponseMissingFieldsFromJSON(json: any): ErrorResponseMissingFields {
    return ErrorResponseMissingFieldsFromJSONTyped(json, false);
}

export function ErrorResponseMissingFieldsFromJSONTyped(json: any, ignoreDiscriminator: boolean): ErrorResponseMissingFields {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
    };
}

export function ErrorResponseMissingFieldsToJSON(value?: ErrorResponseMissingFields | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detail': value['detail'],
    };
}

