/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GeocodeSuccessResponse
 */
export interface GeocodeSuccessResponse {
    /**
     * 
     * @type {number}
     * @memberof GeocodeSuccessResponse
     */
    bIN: number;
    /**
     * 
     * @type {number}
     * @memberof GeocodeSuccessResponse
     */
    latitude: number;
    /**
     * 
     * @type {number}
     * @memberof GeocodeSuccessResponse
     */
    longitude: number;
    /**
     * 
     * @type {number}
     * @memberof GeocodeSuccessResponse
     */
    altitude?: number;
}

/**
 * Check if a given object implements the GeocodeSuccessResponse interface.
 */
export function instanceOfGeocodeSuccessResponse(value: object): value is GeocodeSuccessResponse {
    if (!('bIN' in value) || value['bIN'] === undefined) return false;
    if (!('latitude' in value) || value['latitude'] === undefined) return false;
    if (!('longitude' in value) || value['longitude'] === undefined) return false;
    return true;
}

export function GeocodeSuccessResponseFromJSON(json: any): GeocodeSuccessResponse {
    return GeocodeSuccessResponseFromJSONTyped(json, false);
}

export function GeocodeSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): GeocodeSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'bIN': json['BIN'],
        'latitude': json['latitude'],
        'longitude': json['longitude'],
        'altitude': json['altitude'] == null ? undefined : json['altitude'],
    };
}

export function GeocodeSuccessResponseToJSON(value?: GeocodeSuccessResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'BIN': value['bIN'],
        'latitude': value['latitude'],
        'longitude': value['longitude'],
        'altitude': value['altitude'],
    };
}

