/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The member this install is associated with
 * @export
 * @interface InstallMember
 */
export interface InstallMember {
    /**
     * 
     * @type {string}
     * @memberof InstallMember
     */
    id?: string;
}

/**
 * Check if a given object implements the InstallMember interface.
 */
export function instanceOfInstallMember(value: object): value is InstallMember {
    return true;
}

export function InstallMemberFromJSON(json: any): InstallMember {
    return InstallMemberFromJSONTyped(json, false);
}

export function InstallMemberFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallMember {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function InstallMemberToJSON(value?: InstallMember | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

