/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The building where the install is located. In the case of a structure with multiple buildings, this will be the building whose address makes sense for this install's unit.
 * @export
 * @interface InstallBuilding
 */
export interface InstallBuilding {
    /**
     * 
     * @type {string}
     * @memberof InstallBuilding
     */
    id?: string;
}

/**
 * Check if a given object implements the InstallBuilding interface.
 */
export function instanceOfInstallBuilding(value: object): value is InstallBuilding {
    return true;
}

export function InstallBuildingFromJSON(json: any): InstallBuilding {
    return InstallBuildingFromJSONTyped(json, false);
}

export function InstallBuildingFromJSONTyped(json: any, ignoreDiscriminator: boolean): InstallBuilding {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function InstallBuildingToJSON(value?: InstallBuilding | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

