/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinFormRequest
 */
export interface JoinFormRequest {
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    firstName: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    lastName: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    streetAddress: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    state: string;
    /**
     * 
     * @type {number}
     * @memberof JoinFormRequest
     */
    zip: number;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    apartment: string;
    /**
     * 
     * @type {boolean}
     * @memberof JoinFormRequest
     */
    roofAccess: boolean;
    /**
     * 
     * @type {string}
     * @memberof JoinFormRequest
     */
    referral: string;
    /**
     * 
     * @type {boolean}
     * @memberof JoinFormRequest
     */
    ncl: boolean;
}

/**
 * Check if a given object implements the JoinFormRequest interface.
 */
export function instanceOfJoinFormRequest(value: object): value is JoinFormRequest {
    if (!('firstName' in value) || value['firstName'] === undefined) return false;
    if (!('lastName' in value) || value['lastName'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('phone' in value) || value['phone'] === undefined) return false;
    if (!('streetAddress' in value) || value['streetAddress'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('zip' in value) || value['zip'] === undefined) return false;
    if (!('apartment' in value) || value['apartment'] === undefined) return false;
    if (!('roofAccess' in value) || value['roofAccess'] === undefined) return false;
    if (!('referral' in value) || value['referral'] === undefined) return false;
    if (!('ncl' in value) || value['ncl'] === undefined) return false;
    return true;
}

export function JoinFormRequestFromJSON(json: any): JoinFormRequest {
    return JoinFormRequestFromJSONTyped(json, false);
}

export function JoinFormRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinFormRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'firstName': json['first_name'],
        'lastName': json['last_name'],
        'email': json['email'],
        'phone': json['phone'],
        'streetAddress': json['street_address'],
        'city': json['city'],
        'state': json['state'],
        'zip': json['zip'],
        'apartment': json['apartment'],
        'roofAccess': json['roof_access'],
        'referral': json['referral'],
        'ncl': json['ncl'],
    };
}

export function JoinFormRequestToJSON(value?: JoinFormRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'first_name': value['firstName'],
        'last_name': value['lastName'],
        'email': value['email'],
        'phone': value['phone'],
        'street_address': value['streetAddress'],
        'city': value['city'],
        'state': value['state'],
        'zip': value['zip'],
        'apartment': value['apartment'],
        'roof_access': value['roofAccess'],
        'referral': value['referral'],
        'ncl': value['ncl'],
    };
}

