/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface JoinFormSuccessResponse
 */
export interface JoinFormSuccessResponse {
    /**
     * 
     * @type {string}
     * @memberof JoinFormSuccessResponse
     */
    detail: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormSuccessResponse
     */
    buildingId: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormSuccessResponse
     */
    memberId: string;
    /**
     * 
     * @type {string}
     * @memberof JoinFormSuccessResponse
     */
    installId: string;
    /**
     * 
     * @type {number}
     * @memberof JoinFormSuccessResponse
     */
    installNumber: number;
    /**
     * 
     * @type {boolean}
     * @memberof JoinFormSuccessResponse
     */
    memberExists: boolean;
}

/**
 * Check if a given object implements the JoinFormSuccessResponse interface.
 */
export function instanceOfJoinFormSuccessResponse(value: object): value is JoinFormSuccessResponse {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('buildingId' in value) || value['buildingId'] === undefined) return false;
    if (!('memberId' in value) || value['memberId'] === undefined) return false;
    if (!('installId' in value) || value['installId'] === undefined) return false;
    if (!('installNumber' in value) || value['installNumber'] === undefined) return false;
    if (!('memberExists' in value) || value['memberExists'] === undefined) return false;
    return true;
}

export function JoinFormSuccessResponseFromJSON(json: any): JoinFormSuccessResponse {
    return JoinFormSuccessResponseFromJSONTyped(json, false);
}

export function JoinFormSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): JoinFormSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
        'buildingId': json['building_id'],
        'memberId': json['member_id'],
        'installId': json['install_id'],
        'installNumber': json['install_number'],
        'memberExists': json['member_exists'],
    };
}

export function JoinFormSuccessResponseToJSON(value?: JoinFormSuccessResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detail': value['detail'],
        'building_id': value['buildingId'],
        'member_id': value['memberId'],
        'install_id': value['installId'],
        'install_number': value['installNumber'],
        'member_exists': value['memberExists'],
    };
}

