/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KioskData
 */
export interface KioskData {
    /**
     * 
     * @type {string}
     * @memberof KioskData
     */
    streetAddress: string;
    /**
     * 
     * @type {string}
     * @memberof KioskData
     */
    type: string;
    /**
     * 
     * @type {number}
     * @memberof KioskData
     */
    id: number;
    /**
     * 
     * @type {Array<number>}
     * @memberof KioskData
     */
    coordinates: Array<number>;
    /**
     * 
     * @type {string}
     * @memberof KioskData
     */
    status?: string;
}

/**
 * Check if a given object implements the KioskData interface.
 */
export function instanceOfKioskData(value: object): value is KioskData {
    if (!('streetAddress' in value) || value['streetAddress'] === undefined) return false;
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function KioskDataFromJSON(json: any): KioskData {
    return KioskDataFromJSONTyped(json, false);
}

export function KioskDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): KioskData {
    if (json == null) {
        return json;
    }
    return {
        
        'streetAddress': json['street_address'],
        'type': json['type'],
        'id': json['id'],
        'coordinates': json['coordinates'],
        'status': json['status'] == null ? undefined : json['status'],
    };
}

export function KioskDataToJSON(value?: KioskData | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'street_address': value['streetAddress'],
        'type': value['type'],
        'id': value['id'],
        'coordinates': value['coordinates'],
        'status': value['status'],
    };
}

