/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { BlankEnum } from './BlankEnum';
import {
    instanceOfBlankEnum,
    BlankEnumFromJSON,
    BlankEnumFromJSONTyped,
    BlankEnumToJSON,
} from './BlankEnum';
import type { LinkTypeEnum } from './LinkTypeEnum';
import {
    instanceOfLinkTypeEnum,
    LinkTypeEnumFromJSON,
    LinkTypeEnumFromJSONTyped,
    LinkTypeEnumToJSON,
} from './LinkTypeEnum';

/**
 * @type LinkType
 * The technology used for this link 5Ghz, 60Ghz, fiber, etc.
 * 
 * * `5 GHz` - Five Ghz
 * * `24 GHz` - Twentyfour Ghz
 * * `60 GHz` - Sixty Ghz
 * * `70-80 GHz` - Seventy Eighty Ghz
 * * `VPN` - Vpn
 * * `Fiber` - Fiber
 * * `Ethernet` - Ethernet
 * @export
 */
export type LinkType = BlankEnum | LinkTypeEnum;

export function LinkTypeFromJSON(json: any): LinkType {
    return LinkTypeFromJSONTyped(json, false);
}

export function LinkTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkType {
    if (json == null) {
        return json;
    }
    if (instanceOfBlankEnum(json)) {
        return BlankEnumFromJSONTyped(json, true);
    }
    if (instanceOfLinkTypeEnum(json)) {
        return LinkTypeEnumFromJSONTyped(json, true);
    }

    return {} as any;
}

export function LinkTypeToJSON(value?: LinkType | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfBlankEnum(value)) {
        return BlankEnumToJSON(value as BlankEnum);
    }
    if (instanceOfLinkTypeEnum(value)) {
        return LinkTypeEnumToJSON(value as LinkTypeEnum);
    }

    return {};
}

