/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `5 GHz` - Five Ghz
 * * `24 GHz` - Twentyfour Ghz
 * * `60 GHz` - Sixty Ghz
 * * `70-80 GHz` - Seventy Eighty Ghz
 * * `VPN` - Vpn
 * * `Fiber` - Fiber
 * * `Ethernet` - Ethernet
 * @export
 */
export const LinkTypeEnum = {
    _5Ghz: '5 GHz',
    _24Ghz: '24 GHz',
    _60Ghz: '60 GHz',
    _7080Ghz: '70-80 GHz',
    Vpn: 'VPN',
    Fiber: 'Fiber',
    Ethernet: 'Ethernet'
} as const;
export type LinkTypeEnum = typeof LinkTypeEnum[keyof typeof LinkTypeEnum];


export function instanceOfLinkTypeEnum(value: any): boolean {
    for (const key in LinkTypeEnum) {
        if (Object.prototype.hasOwnProperty.call(LinkTypeEnum, key)) {
            if (LinkTypeEnum[key as keyof typeof LinkTypeEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LinkTypeEnumFromJSON(json: any): LinkTypeEnum {
    return LinkTypeEnumFromJSONTyped(json, false);
}

export function LinkTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkTypeEnum {
    return json as LinkTypeEnum;
}

export function LinkTypeEnumToJSON(value?: LinkTypeEnum | null): any {
    return value as any;
}

