/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Inactive` - Inactive
 * * `Planned` - Planned
 * * `Active` - Active
 * @export
 */
export const LinkStatusEnum = {
    Inactive: 'Inactive',
    Planned: 'Planned',
    Active: 'Active'
} as const;
export type LinkStatusEnum = typeof LinkStatusEnum[keyof typeof LinkStatusEnum];


export function instanceOfLinkStatusEnum(value: any): boolean {
    for (const key in LinkStatusEnum) {
        if (Object.prototype.hasOwnProperty.call(LinkStatusEnum, key)) {
            if (LinkStatusEnum[key as keyof typeof LinkStatusEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function LinkStatusEnumFromJSON(json: any): LinkStatusEnum {
    return LinkStatusEnumFromJSONTyped(json, false);
}

export function LinkStatusEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkStatusEnum {
    return json as LinkStatusEnum;
}

export function LinkStatusEnumToJSON(value?: LinkStatusEnum | null): any {
    return value as any;
}

