/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The device on one side of this network link, from/to are not meaningful except to disambiguate
 * @export
 * @interface LinkFromDevice
 */
export interface LinkFromDevice {
    /**
     * 
     * @type {string}
     * @memberof LinkFromDevice
     */
    id?: string;
}

/**
 * Check if a given object implements the LinkFromDevice interface.
 */
export function instanceOfLinkFromDevice(value: object): value is LinkFromDevice {
    return true;
}

export function LinkFromDeviceFromJSON(json: any): LinkFromDevice {
    return LinkFromDeviceFromJSONTyped(json, false);
}

export function LinkFromDeviceFromJSONTyped(json: any, ignoreDiscriminator: boolean): LinkFromDevice {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function LinkFromDeviceToJSON(value?: LinkFromDevice | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

