/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LinkFromDevice } from './LinkFromDevice';
import {
    LinkFromDeviceFromJSON,
    LinkFromDeviceFromJSONTyped,
    LinkFromDeviceToJSON,
} from './LinkFromDevice';
import type { LinkStatusEnum } from './LinkStatusEnum';
import {
    LinkStatusEnumFromJSON,
    LinkStatusEnumFromJSONTyped,
    LinkStatusEnumToJSON,
} from './LinkStatusEnum';
import type { LinkType } from './LinkType';
import {
    LinkTypeFromJSON,
    LinkTypeFromJSONTyped,
    LinkTypeToJSON,
} from './LinkType';

/**
 * A  ModelSerializer MixIn which sets `NestedKeyObjectRelatedField` as the default field class
 * to use for the foreign key fields
 * @export
 * @interface Link
 */
export interface Link {
    /**
     * 
     * @type {string}
     * @memberof Link
     */
    readonly id: string;
    /**
     * The current status of this link
     * 
     * * `Inactive` - Inactive
     * * `Planned` - Planned
     * * `Active` - Active
     * @type {LinkStatusEnum}
     * @memberof Link
     */
    status: LinkStatusEnum;
    /**
     * 
     * @type {LinkType}
     * @memberof Link
     */
    type?: LinkType | null;
    /**
     * The date this link was created
     * @type {Date}
     * @memberof Link
     */
    installDate?: Date | null;
    /**
     * The date this link was powered off, disassembled, or abandoned
     * @type {Date}
     * @memberof Link
     */
    abandonDate?: Date | null;
    /**
     * A short description of "where to where" this link connects in human readable language
     * @type {string}
     * @memberof Link
     */
    description?: string | null;
    /**
     * A free-form text description of this Link, to track any additional information.
     * @type {string}
     * @memberof Link
     */
    notes?: string | null;
    /**
     * The UUID used to indentify this link in UISP (if applicable)
     * @type {string}
     * @memberof Link
     */
    uispId?: string | null;
    /**
     * 
     * @type {LinkFromDevice}
     * @memberof Link
     */
    fromDevice: LinkFromDevice;
    /**
     * 
     * @type {LinkFromDevice}
     * @memberof Link
     */
    toDevice: LinkFromDevice;
}



/**
 * Check if a given object implements the Link interface.
 */
export function instanceOfLink(value: object): value is Link {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('fromDevice' in value) || value['fromDevice'] === undefined) return false;
    if (!('toDevice' in value) || value['toDevice'] === undefined) return false;
    return true;
}

export function LinkFromJSON(json: any): Link {
    return LinkFromJSONTyped(json, false);
}

export function LinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): Link {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'status': LinkStatusEnumFromJSON(json['status']),
        'type': json['type'] == null ? undefined : LinkTypeFromJSON(json['type']),
        'installDate': json['install_date'] == null ? undefined : (new Date(json['install_date'])),
        'abandonDate': json['abandon_date'] == null ? undefined : (new Date(json['abandon_date'])),
        'description': json['description'] == null ? undefined : json['description'],
        'notes': json['notes'] == null ? undefined : json['notes'],
        'uispId': json['uisp_id'] == null ? undefined : json['uisp_id'],
        'fromDevice': LinkFromDeviceFromJSON(json['from_device']),
        'toDevice': LinkFromDeviceFromJSON(json['to_device']),
    };
}

export function LinkToJSON(value?: Omit<Link, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': LinkStatusEnumToJSON(value['status']),
        'type': LinkTypeToJSON(value['type']),
        'install_date': value['installDate'] == null ? undefined : ((value['installDate'] as any).toISOString().substring(0,10)),
        'abandon_date': value['abandonDate'] == null ? undefined : ((value['abandonDate'] as any).toISOString().substring(0,10)),
        'description': value['description'],
        'notes': value['notes'],
        'uisp_id': value['uispId'],
        'from_device': LinkFromDeviceToJSON(value['fromDevice']),
        'to_device': LinkFromDeviceToJSON(value['toDevice']),
    };
}

