/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * The building on one side of this LOS, from/to are not meaningful except to disambiguate
 * @export
 * @interface LOSFromBuilding
 */
export interface LOSFromBuilding {
    /**
     * 
     * @type {string}
     * @memberof LOSFromBuilding
     */
    id?: string;
}

/**
 * Check if a given object implements the LOSFromBuilding interface.
 */
export function instanceOfLOSFromBuilding(value: object): value is LOSFromBuilding {
    return true;
}

export function LOSFromBuildingFromJSON(json: any): LOSFromBuilding {
    return LOSFromBuildingFromJSONTyped(json, false);
}

export function LOSFromBuildingFromJSONTyped(json: any, ignoreDiscriminator: boolean): LOSFromBuilding {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function LOSFromBuildingToJSON(value?: LOSFromBuilding | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

