/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapDataSector
 */
export interface MapDataSector {
    /**
     * 
     * @type {number}
     * @memberof MapDataSector
     */
    readonly nodeId: number | null;
    /**
     * The radius to display this sector on the map (in km)
     * @type {number}
     * @memberof MapDataSector
     */
    radius: number;
    /**
     * The compass heading that this sector is pointed towards
     * @type {number}
     * @memberof MapDataSector
     */
    azimuth: number;
    /**
     * The approximate width of the beam this sector produces
     * @type {number}
     * @memberof MapDataSector
     */
    width: number;
    /**
     * 
     * @type {string}
     * @memberof MapDataSector
     */
    readonly status: string;
    /**
     * 
     * @type {number}
     * @memberof MapDataSector
     */
    installDate: number;
}

/**
 * Check if a given object implements the MapDataSector interface.
 */
export function instanceOfMapDataSector(value: object): value is MapDataSector {
    if (!('nodeId' in value) || value['nodeId'] === undefined) return false;
    if (!('radius' in value) || value['radius'] === undefined) return false;
    if (!('azimuth' in value) || value['azimuth'] === undefined) return false;
    if (!('width' in value) || value['width'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('installDate' in value) || value['installDate'] === undefined) return false;
    return true;
}

export function MapDataSectorFromJSON(json: any): MapDataSector {
    return MapDataSectorFromJSONTyped(json, false);
}

export function MapDataSectorFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapDataSector {
    if (json == null) {
        return json;
    }
    return {
        
        'nodeId': json['nodeId'],
        'radius': json['radius'],
        'azimuth': json['azimuth'],
        'width': json['width'],
        'status': json['status'],
        'installDate': json['installDate'],
    };
}

export function MapDataSectorToJSON(value?: Omit<MapDataSector, 'nodeId'|'status'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'radius': value['radius'],
        'azimuth': value['azimuth'],
        'width': value['width'],
        'installDate': value['installDate'],
    };
}

