/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MapDataLink
 */
export interface MapDataLink {
    /**
     * 
     * @type {number}
     * @memberof MapDataLink
     */
    readonly from: number | null;
    /**
     * 
     * @type {number}
     * @memberof MapDataLink
     */
    readonly to: number | null;
    /**
     * 
     * @type {string}
     * @memberof MapDataLink
     */
    readonly status: string;
    /**
     * 
     * @type {number}
     * @memberof MapDataLink
     */
    installDate: number;
}

/**
 * Check if a given object implements the MapDataLink interface.
 */
export function instanceOfMapDataLink(value: object): value is MapDataLink {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('installDate' in value) || value['installDate'] === undefined) return false;
    return true;
}

export function MapDataLinkFromJSON(json: any): MapDataLink {
    return MapDataLinkFromJSONTyped(json, false);
}

export function MapDataLinkFromJSONTyped(json: any, ignoreDiscriminator: boolean): MapDataLink {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
        'status': json['status'],
        'installDate': json['installDate'],
    };
}

export function MapDataLinkToJSON(value?: Omit<MapDataLink, 'from'|'to'|'status'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'installDate': value['installDate'],
    };
}

