/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NetworkNumberAssignmentRequest
 */
export interface NetworkNumberAssignmentRequest {
    /**
     * 
     * @type {string}
     * @memberof NetworkNumberAssignmentRequest
     */
    password: string;
    /**
     * 
     * @type {number}
     * @memberof NetworkNumberAssignmentRequest
     */
    installNumber: number;
}

/**
 * Check if a given object implements the NetworkNumberAssignmentRequest interface.
 */
export function instanceOfNetworkNumberAssignmentRequest(value: object): value is NetworkNumberAssignmentRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('installNumber' in value) || value['installNumber'] === undefined) return false;
    return true;
}

export function NetworkNumberAssignmentRequestFromJSON(json: any): NetworkNumberAssignmentRequest {
    return NetworkNumberAssignmentRequestFromJSONTyped(json, false);
}

export function NetworkNumberAssignmentRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): NetworkNumberAssignmentRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'installNumber': json['install_number'],
    };
}

export function NetworkNumberAssignmentRequestToJSON(value?: NetworkNumberAssignmentRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'install_number': value['installNumber'],
    };
}

