/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NNFormSuccessResponse
 */
export interface NNFormSuccessResponse {
    /**
     * 
     * @type {string}
     * @memberof NNFormSuccessResponse
     */
    detail: string;
    /**
     * 
     * @type {string}
     * @memberof NNFormSuccessResponse
     */
    buildingId: string;
    /**
     * 
     * @type {string}
     * @memberof NNFormSuccessResponse
     */
    installId: string;
    /**
     * 
     * @type {number}
     * @memberof NNFormSuccessResponse
     */
    installNumber: number;
    /**
     * 
     * @type {number}
     * @memberof NNFormSuccessResponse
     */
    networkNumber: number;
    /**
     * 
     * @type {boolean}
     * @memberof NNFormSuccessResponse
     */
    created: boolean;
}

/**
 * Check if a given object implements the NNFormSuccessResponse interface.
 */
export function instanceOfNNFormSuccessResponse(value: object): value is NNFormSuccessResponse {
    if (!('detail' in value) || value['detail'] === undefined) return false;
    if (!('buildingId' in value) || value['buildingId'] === undefined) return false;
    if (!('installId' in value) || value['installId'] === undefined) return false;
    if (!('installNumber' in value) || value['installNumber'] === undefined) return false;
    if (!('networkNumber' in value) || value['networkNumber'] === undefined) return false;
    if (!('created' in value) || value['created'] === undefined) return false;
    return true;
}

export function NNFormSuccessResponseFromJSON(json: any): NNFormSuccessResponse {
    return NNFormSuccessResponseFromJSONTyped(json, false);
}

export function NNFormSuccessResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): NNFormSuccessResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'detail': json['detail'],
        'buildingId': json['building_id'],
        'installId': json['install_id'],
        'installNumber': json['install_number'],
        'networkNumber': json['network_number'],
        'created': json['created'],
    };
}

export function NNFormSuccessResponseToJSON(value?: NNFormSuccessResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'detail': value['detail'],
        'building_id': value['buildingId'],
        'install_id': value['installId'],
        'install_number': value['installNumber'],
        'network_number': value['networkNumber'],
        'created': value['created'],
    };
}

