/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * A reference to a Device object, via one or more of the following keys: ['id']
 * @export
 * @interface NodeDevicesInner
 */
export interface NodeDevicesInner {
    /**
     * 
     * @type {string}
     * @memberof NodeDevicesInner
     */
    id?: string;
}

/**
 * Check if a given object implements the NodeDevicesInner interface.
 */
export function instanceOfNodeDevicesInner(value: object): value is NodeDevicesInner {
    return true;
}

export function NodeDevicesInnerFromJSON(json: any): NodeDevicesInner {
    return NodeDevicesInnerFromJSONTyped(json, false);
}

export function NodeDevicesInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): NodeDevicesInner {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
    };
}

export function NodeDevicesInnerToJSON(value?: NodeDevicesInner | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
    };
}

