/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Building } from './Building';
import {
    BuildingFromJSON,
    BuildingFromJSONTyped,
    BuildingToJSON,
} from './Building';

/**
 * 
 * @export
 * @interface PaginatedBuildingList
 */
export interface PaginatedBuildingList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedBuildingList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBuildingList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedBuildingList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Building>}
     * @memberof PaginatedBuildingList
     */
    results: Array<Building>;
}

/**
 * Check if a given object implements the PaginatedBuildingList interface.
 */
export function instanceOfPaginatedBuildingList(value: object): value is PaginatedBuildingList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedBuildingListFromJSON(json: any): PaginatedBuildingList {
    return PaginatedBuildingListFromJSONTyped(json, false);
}

export function PaginatedBuildingListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedBuildingList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(BuildingFromJSON)),
    };
}

export function PaginatedBuildingListToJSON(value?: PaginatedBuildingList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(BuildingToJSON)),
    };
}

