/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AccessPoint } from './AccessPoint';
import {
    AccessPointFromJSON,
    AccessPointFromJSONTyped,
    AccessPointToJSON,
} from './AccessPoint';

/**
 * 
 * @export
 * @interface PaginatedAccessPointList
 */
export interface PaginatedAccessPointList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedAccessPointList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccessPointList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedAccessPointList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<AccessPoint>}
     * @memberof PaginatedAccessPointList
     */
    results: Array<AccessPoint>;
}

/**
 * Check if a given object implements the PaginatedAccessPointList interface.
 */
export function instanceOfPaginatedAccessPointList(value: object): value is PaginatedAccessPointList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedAccessPointListFromJSON(json: any): PaginatedAccessPointList {
    return PaginatedAccessPointListFromJSONTyped(json, false);
}

export function PaginatedAccessPointListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedAccessPointList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(AccessPointFromJSON)),
    };
}

export function PaginatedAccessPointListToJSON(value?: PaginatedAccessPointList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(AccessPointToJSON)),
    };
}

