/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Install } from './Install';
import {
    InstallFromJSON,
    InstallFromJSONTyped,
    InstallToJSON,
} from './Install';

/**
 * 
 * @export
 * @interface PaginatedInstallList
 */
export interface PaginatedInstallList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedInstallList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInstallList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedInstallList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Install>}
     * @memberof PaginatedInstallList
     */
    results: Array<Install>;
}

/**
 * Check if a given object implements the PaginatedInstallList interface.
 */
export function instanceOfPaginatedInstallList(value: object): value is PaginatedInstallList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedInstallListFromJSON(json: any): PaginatedInstallList {
    return PaginatedInstallListFromJSONTyped(json, false);
}

export function PaginatedInstallListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedInstallList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(InstallFromJSON)),
    };
}

export function PaginatedInstallListToJSON(value?: PaginatedInstallList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(InstallToJSON)),
    };
}

