/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { QueryForm } from './QueryForm';
import {
    QueryFormFromJSON,
    QueryFormFromJSONTyped,
    QueryFormToJSON,
} from './QueryForm';

/**
 * 
 * @export
 * @interface PaginatedQueryFormList
 */
export interface PaginatedQueryFormList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedQueryFormList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedQueryFormList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedQueryFormList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<QueryForm>}
     * @memberof PaginatedQueryFormList
     */
    results: Array<QueryForm>;
}

/**
 * Check if a given object implements the PaginatedQueryFormList interface.
 */
export function instanceOfPaginatedQueryFormList(value: object): value is PaginatedQueryFormList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedQueryFormListFromJSON(json: any): PaginatedQueryFormList {
    return PaginatedQueryFormListFromJSONTyped(json, false);
}

export function PaginatedQueryFormListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedQueryFormList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(QueryFormFromJSON)),
    };
}

export function PaginatedQueryFormListToJSON(value?: PaginatedQueryFormList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(QueryFormToJSON)),
    };
}

