/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Node } from './Node';
import {
    NodeFromJSON,
    NodeFromJSONTyped,
    NodeToJSON,
} from './Node';

/**
 * 
 * @export
 * @interface PaginatedNodeList
 */
export interface PaginatedNodeList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedNodeList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedNodeList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedNodeList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Node>}
     * @memberof PaginatedNodeList
     */
    results: Array<Node>;
}

/**
 * Check if a given object implements the PaginatedNodeList interface.
 */
export function instanceOfPaginatedNodeList(value: object): value is PaginatedNodeList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedNodeListFromJSON(json: any): PaginatedNodeList {
    return PaginatedNodeListFromJSONTyped(json, false);
}

export function PaginatedNodeListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedNodeList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(NodeFromJSON)),
    };
}

export function PaginatedNodeListToJSON(value?: PaginatedNodeList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(NodeToJSON)),
    };
}

