/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';

/**
 * 
 * @export
 * @interface PaginatedLinkList
 */
export interface PaginatedLinkList {
    /**
     * 
     * @type {number}
     * @memberof PaginatedLinkList
     */
    count: number;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinkList
     */
    next?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PaginatedLinkList
     */
    previous?: string | null;
    /**
     * 
     * @type {Array<Link>}
     * @memberof PaginatedLinkList
     */
    results: Array<Link>;
}

/**
 * Check if a given object implements the PaginatedLinkList interface.
 */
export function instanceOfPaginatedLinkList(value: object): value is PaginatedLinkList {
    if (!('count' in value) || value['count'] === undefined) return false;
    if (!('results' in value) || value['results'] === undefined) return false;
    return true;
}

export function PaginatedLinkListFromJSON(json: any): PaginatedLinkList {
    return PaginatedLinkListFromJSONTyped(json, false);
}

export function PaginatedLinkListFromJSONTyped(json: any, ignoreDiscriminator: boolean): PaginatedLinkList {
    if (json == null) {
        return json;
    }
    return {
        
        'count': json['count'],
        'next': json['next'] == null ? undefined : json['next'],
        'previous': json['previous'] == null ? undefined : json['previous'],
        'results': ((json['results'] as Array<any>).map(LinkFromJSON)),
    };
}

export function PaginatedLinkListToJSON(value?: PaginatedLinkList | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'count': value['count'],
        'next': value['next'],
        'previous': value['previous'],
        'results': ((value['results'] as Array<any>).map(LinkToJSON)),
    };
}

