/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { LOSFromBuilding } from './LOSFromBuilding';
import {
    LOSFromBuildingFromJSON,
    LOSFromBuildingFromJSONTyped,
    LOSFromBuildingToJSON,
} from './LOSFromBuilding';
import type { SourceEnum } from './SourceEnum';
import {
    SourceEnumFromJSON,
    SourceEnumFromJSONTyped,
    SourceEnumToJSON,
} from './SourceEnum';

/**
 * A  ModelSerializer MixIn which sets `NestedKeyObjectRelatedField` as the default field class
 * to use for the foreign key fields
 * @export
 * @interface PatchedLOS
 */
export interface PatchedLOS {
    /**
     * 
     * @type {string}
     * @memberof PatchedLOS
     */
    readonly id?: string;
    /**
     * The date we conducted the analysis that concluded this LOS exists. Important since new buildings might have been built which block the LOS after this date
     * @type {Date}
     * @memberof PatchedLOS
     */
    analysisDate?: Date | null;
    /**
     * The source of information that tells us this LOS exists
     * 
     * * `Human Annotated` - Human Annotated
     * * `Existing Link` - Existing Link
     * @type {SourceEnum}
     * @memberof PatchedLOS
     */
    source?: SourceEnum;
    /**
     * A free-form text description of this LOS, to track any additional information.
     * @type {string}
     * @memberof PatchedLOS
     */
    notes?: string | null;
    /**
     * 
     * @type {LOSFromBuilding}
     * @memberof PatchedLOS
     */
    fromBuilding?: LOSFromBuilding;
    /**
     * 
     * @type {LOSFromBuilding}
     * @memberof PatchedLOS
     */
    toBuilding?: LOSFromBuilding;
}



/**
 * Check if a given object implements the PatchedLOS interface.
 */
export function instanceOfPatchedLOS(value: object): value is PatchedLOS {
    return true;
}

export function PatchedLOSFromJSON(json: any): PatchedLOS {
    return PatchedLOSFromJSONTyped(json, false);
}

export function PatchedLOSFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchedLOS {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'analysisDate': json['analysis_date'] == null ? undefined : (new Date(json['analysis_date'])),
        'source': json['source'] == null ? undefined : SourceEnumFromJSON(json['source']),
        'notes': json['notes'] == null ? undefined : json['notes'],
        'fromBuilding': json['from_building'] == null ? undefined : LOSFromBuildingFromJSON(json['from_building']),
        'toBuilding': json['to_building'] == null ? undefined : LOSFromBuildingFromJSON(json['to_building']),
    };
}

export function PatchedLOSToJSON(value?: Omit<PatchedLOS, 'id'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'analysis_date': value['analysisDate'] == null ? undefined : ((value['analysisDate'] as any).toISOString().substring(0,10)),
        'source': SourceEnumToJSON(value['source']),
        'notes': value['notes'],
        'from_building': LOSFromBuildingToJSON(value['fromBuilding']),
        'to_building': LOSFromBuildingToJSON(value['toBuilding']),
    };
}

