/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Status195Enum } from './Status195Enum';
import {
    Status195EnumFromJSON,
    Status195EnumFromJSONTyped,
    Status195EnumToJSON,
} from './Status195Enum';

/**
 * Objects which approximate the CSV output from the legacy docs query form. These approximately
 * correspond to the spreadsheet row format, by flattening attributes across many models into a
 * single JSON object
 * @export
 * @interface QueryForm
 */
export interface QueryForm {
    /**
     * 
     * @type {number}
     * @memberof QueryForm
     */
    readonly installNumber: number;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    streetAddress: string;
    /**
     * Line 2 of this install's mailing address
     * @type {string}
     * @memberof QueryForm
     */
    unit?: string | null;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    city: string;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    state: string;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    zipCode: string;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    phoneNumber: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryForm
     */
    additionalPhoneNumbers: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    primaryEmailAddress: string;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    stripeEmailAddress: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof QueryForm
     */
    additionalEmailAddresses: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof QueryForm
     */
    readonly notes: string;
    /**
     * 
     * @type {number}
     * @memberof QueryForm
     */
    networkNumber: number | null;
    /**
     * The current status of this install
     * 
     * * `Request Received` - Request Received
     * * `Pending` - Pending
     * * `Blocked` - Blocked
     * * `Active` - Active
     * * `Inactive` - Inactive
     * * `Closed` - Closed
     * * `NN Reassigned` - Nn Reassigned
     * @type {Status195Enum}
     * @memberof QueryForm
     */
    status: Status195Enum;
}



/**
 * Check if a given object implements the QueryForm interface.
 */
export function instanceOfQueryForm(value: object): value is QueryForm {
    if (!('installNumber' in value) || value['installNumber'] === undefined) return false;
    if (!('streetAddress' in value) || value['streetAddress'] === undefined) return false;
    if (!('city' in value) || value['city'] === undefined) return false;
    if (!('state' in value) || value['state'] === undefined) return false;
    if (!('zipCode' in value) || value['zipCode'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('phoneNumber' in value) || value['phoneNumber'] === undefined) return false;
    if (!('additionalPhoneNumbers' in value) || value['additionalPhoneNumbers'] === undefined) return false;
    if (!('primaryEmailAddress' in value) || value['primaryEmailAddress'] === undefined) return false;
    if (!('stripeEmailAddress' in value) || value['stripeEmailAddress'] === undefined) return false;
    if (!('additionalEmailAddresses' in value) || value['additionalEmailAddresses'] === undefined) return false;
    if (!('notes' in value) || value['notes'] === undefined) return false;
    if (!('networkNumber' in value) || value['networkNumber'] === undefined) return false;
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function QueryFormFromJSON(json: any): QueryForm {
    return QueryFormFromJSONTyped(json, false);
}

export function QueryFormFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryForm {
    if (json == null) {
        return json;
    }
    return {
        
        'installNumber': json['install_number'],
        'streetAddress': json['street_address'],
        'unit': json['unit'] == null ? undefined : json['unit'],
        'city': json['city'],
        'state': json['state'],
        'zipCode': json['zip_code'],
        'name': json['name'],
        'phoneNumber': json['phone_number'],
        'additionalPhoneNumbers': json['additional_phone_numbers'],
        'primaryEmailAddress': json['primary_email_address'],
        'stripeEmailAddress': json['stripe_email_address'],
        'additionalEmailAddresses': json['additional_email_addresses'],
        'notes': json['notes'],
        'networkNumber': json['network_number'],
        'status': Status195EnumFromJSON(json['status']),
    };
}

export function QueryFormToJSON(value?: Omit<QueryForm, 'install_number'|'notes'> | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'street_address': value['streetAddress'],
        'unit': value['unit'],
        'city': value['city'],
        'state': value['state'],
        'zip_code': value['zipCode'],
        'name': value['name'],
        'phone_number': value['phoneNumber'],
        'additional_phone_numbers': value['additionalPhoneNumbers'],
        'primary_email_address': value['primaryEmailAddress'],
        'stripe_email_address': value['stripeEmailAddress'],
        'additional_email_addresses': value['additionalEmailAddresses'],
        'network_number': value['networkNumber'],
        'status': Status195EnumToJSON(value['status']),
    };
}

