/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Human Annotated` - Human Annotated
 * * `Existing Link` - Existing Link
 * @export
 */
export const SourceEnum = {
    HumanAnnotated: 'Human Annotated',
    ExistingLink: 'Existing Link'
} as const;
export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];


export function instanceOfSourceEnum(value: any): boolean {
    for (const key in SourceEnum) {
        if (Object.prototype.hasOwnProperty.call(SourceEnum, key)) {
            if (SourceEnum[key as keyof typeof SourceEnum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function SourceEnumFromJSON(json: any): SourceEnum {
    return SourceEnumFromJSONTyped(json, false);
}

export function SourceEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SourceEnum {
    return json as SourceEnum;
}

export function SourceEnumToJSON(value?: SourceEnum | null): any {
    return value as any;
}

