/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Request Received` - Request Received
 * * `Pending` - Pending
 * * `Blocked` - Blocked
 * * `Active` - Active
 * * `Inactive` - Inactive
 * * `Closed` - Closed
 * * `NN Reassigned` - Nn Reassigned
 * @export
 */
export const Status195Enum = {
    RequestReceived: 'Request Received',
    Pending: 'Pending',
    Blocked: 'Blocked',
    Active: 'Active',
    Inactive: 'Inactive',
    Closed: 'Closed',
    NnReassigned: 'NN Reassigned'
} as const;
export type Status195Enum = typeof Status195Enum[keyof typeof Status195Enum];


export function instanceOfStatus195Enum(value: any): boolean {
    for (const key in Status195Enum) {
        if (Object.prototype.hasOwnProperty.call(Status195Enum, key)) {
            if (Status195Enum[key as keyof typeof Status195Enum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function Status195EnumFromJSON(json: any): Status195Enum {
    return Status195EnumFromJSONTyped(json, false);
}

export function Status195EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status195Enum {
    return json as Status195Enum;
}

export function Status195EnumToJSON(value?: Status195Enum | null): any {
    return value as any;
}

