/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Inactive` - Inactive
 * * `Active` - Active
 * * `Planned` - Planned
 * @export
 */
export const Status2a6Enum = {
    Inactive: 'Inactive',
    Active: 'Active',
    Planned: 'Planned'
} as const;
export type Status2a6Enum = typeof Status2a6Enum[keyof typeof Status2a6Enum];


export function instanceOfStatus2a6Enum(value: any): boolean {
    for (const key in Status2a6Enum) {
        if (Object.prototype.hasOwnProperty.call(Status2a6Enum, key)) {
            if (Status2a6Enum[key as keyof typeof Status2a6Enum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function Status2a6EnumFromJSON(json: any): Status2a6Enum {
    return Status2a6EnumFromJSONTyped(json, false);
}

export function Status2a6EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): Status2a6Enum {
    return json as Status2a6Enum;
}

export function Status2a6EnumToJSON(value?: Status2a6Enum | null): any {
    return value as any;
}

