/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * * `Standard` - Standard
 * * `Hub` - Hub
 * * `Supernode` - Supernode
 * * `POP` - Pop
 * * `AP` - Ap
 * * `Remote` - Remote
 * @export
 */
export const TypeB10Enum = {
    Standard: 'Standard',
    Hub: 'Hub',
    Supernode: 'Supernode',
    Pop: 'POP',
    Ap: 'AP',
    Remote: 'Remote'
} as const;
export type TypeB10Enum = typeof TypeB10Enum[keyof typeof TypeB10Enum];


export function instanceOfTypeB10Enum(value: any): boolean {
    for (const key in TypeB10Enum) {
        if (Object.prototype.hasOwnProperty.call(TypeB10Enum, key)) {
            if (TypeB10Enum[key as keyof typeof TypeB10Enum] === value) {
                return true;
            }
        }
    }
    return false;
}

export function TypeB10EnumFromJSON(json: any): TypeB10Enum {
    return TypeB10EnumFromJSONTyped(json, false);
}

export function TypeB10EnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TypeB10Enum {
    return json as TypeB10Enum;
}

export function TypeB10EnumToJSON(value?: TypeB10Enum | null): any {
    return value as any;
}

