apiVersion: v1
kind: ConfigMap
metadata:
  name: meshforms-config
data:
  JOIN_RECORD_BUCKET_NAME: {{ .Values.meshforms.s3_bucket_name }}
  JOIN_RECORD_PREFIX: {{ .Values.meshforms.s3_base_name }}
  AWS_REGION: {{ .Values.aws.region }}
