apiVersion: v1
kind: ConfigMap
metadata:
  name: meshforms-config
data:
  MESHFORMS_ENVIRONMENT: {{ .Values.meshforms.environment }}
  JOIN_RECORD_BUCKET_NAME: {{ .Values.meshforms.s3_bucket_name }}
  JOIN_RECORD_PREFIX: {{ .Values.meshforms.s3_base_name }}
  AWS_REGION: {{ .Values.aws.region }}
  PANO_URL: {{ .Values.pano.url }}
  ENABLE_PANO_UI: {{ .Values.pano.enable }}
