apiVersion: v1
kind: Secret
metadata:
  name: meshforms-secrets
  namespace: {{ .Values.meshforms_app_namespace }}
type: Opaque
data:
  S3_ACCESS_KEY: {{ .Values.aws.access_key | b64enc | quote }}
  S3_SECRET_KEY: {{ .Values.aws.secret_key | b64enc | quote }}
  S3_BUCKET_NAME: {{ .Values.s3_bucket_name | b64enc | quote }}
  S3_BASE_NAME: {{ .Values.s3_base_name | b64enc | quote }}
  NEXT_PUBLIC_MESHDB_URL: {{ .Values.meshforms.meshdb_url | b64enc | quote }}
