apiVersion: v1
kind: Secret
metadata:
  name: meshforms-secrets
type: Opaque
data:
  AWS_ACCESS_KEY_ID: {{ .Values.aws.access_key | b64enc | quote }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.aws.secret_key | b64enc | quote }}
  S3_BUCKET_NAME: {{ .Values.meshforms.s3_bucket_name | b64enc | quote }}
  S3_BASE_NAME: {{ .Values.meshforms.s3_base_name | b64enc | quote }}
  MESHDB_URL: {{ .Values.meshforms.meshdb_url | b64enc | quote }}
  RECAPTCHA_V2_KEY: {{ .Values.meshforms.recaptcha_v2_key | default "" | b64enc | quote }}
  RECAPTCHA_V3_KEY: {{ .Values.meshforms.recaptcha_v3_key | default "" | b64enc | quote }}
  RUM_APPLICATION_ID: {{ .Values.meshforms.rum_application_id | default "" | b64enc | quote }}
  RUM_CLIENT_TOKEN: {{ .Values.meshforms.rum_client_token | default "" | b64enc | quote }}
