/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';

/**
 * 
 */
export class APIStatusApi extends runtime.BaseAPI {

    /**
     * This endpoint can be used by clients to determine the health status of this API. This API always returns 200 status codes, accepts no input, and has no side effects. It always returns the string \"We\'re meshin\'.\"
     * Check API status
     */
    async apiV1RetrieveRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * This endpoint can be used by clients to determine the health status of this API. This API always returns 200 status codes, accepts no input, and has no side effects. It always returns the string \"We\'re meshin\'.\"
     * Check API status
     */
    async apiV1Retrieve(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiV1RetrieveRaw(initOverrides);
        return await response.value();
    }

}
