/* tslint:disable */
/* eslint-disable */
/**
 * MeshDB Data API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ErrorResponse,
  JoinFormRequest,
  JoinFormSuccessResponse,
  NNFormSuccessResponse,
  NetworkNumberAssignmentRequest,
} from '../models/index';
import {
    ErrorResponseFromJSON,
    ErrorResponseToJSON,
    JoinFormRequestFromJSON,
    JoinFormRequestToJSON,
    JoinFormSuccessResponseFromJSON,
    JoinFormSuccessResponseToJSON,
    NNFormSuccessResponseFromJSON,
    NNFormSuccessResponseToJSON,
    NetworkNumberAssignmentRequestFromJSON,
    NetworkNumberAssignmentRequestToJSON,
} from '../models/index';

export interface ApiV1JoinCreateRequest {
    joinFormRequest: JoinFormRequest;
}

export interface ApiV1NnAssignCreateRequest {
    networkNumberAssignmentRequest: NetworkNumberAssignmentRequest;
}

/**
 * 
 */
export class UserFormsApi extends runtime.BaseAPI {

    /**
     * Register a new request for a potential mesh Install. Used by the join form posted on the nycmesh.net website
     */
    async apiV1JoinCreateRaw(requestParameters: ApiV1JoinCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<JoinFormSuccessResponse>> {
        if (requestParameters['joinFormRequest'] == null) {
            throw new runtime.RequiredError(
                'joinFormRequest',
                'Required parameter "joinFormRequest" was null or undefined when calling apiV1JoinCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/join/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: JoinFormRequestToJSON(requestParameters['joinFormRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => JoinFormSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Register a new request for a potential mesh Install. Used by the join form posted on the nycmesh.net website
     */
    async apiV1JoinCreate(requestParameters: ApiV1JoinCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<JoinFormSuccessResponse> {
        const response = await this.apiV1JoinCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Takes an install number, and assigns the install a network number, deduping using the other buildings in our database.
     * Assign a network number to a given Install object. Used by the NN Assignment form
     */
    async apiV1NnAssignCreateRaw(requestParameters: ApiV1NnAssignCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<NNFormSuccessResponse>> {
        if (requestParameters['networkNumberAssignmentRequest'] == null) {
            throw new runtime.RequiredError(
                'networkNumberAssignmentRequest',
                'Required parameter "networkNumberAssignmentRequest" was null or undefined when calling apiV1NnAssignCreate().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.apiKey) {
            headerParameters["Authorization"] = await this.configuration.apiKey("Authorization"); // tokenAuth authentication
        }

        const response = await this.request({
            path: `/api/v1/nn-assign/`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: NetworkNumberAssignmentRequestToJSON(requestParameters['networkNumberAssignmentRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => NNFormSuccessResponseFromJSON(jsonValue));
    }

    /**
     * Takes an install number, and assigns the install a network number, deduping using the other buildings in our database.
     * Assign a network number to a given Install object. Used by the NN Assignment form
     */
    async apiV1NnAssignCreate(requestParameters: ApiV1NnAssignCreateRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<NNFormSuccessResponse> {
        const response = await this.apiV1NnAssignCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
