replicaCount: 3

image:
  repository: willnilges/meshforms
  pullPolicy: Always

imagePullSecrets: []
nameOverride: "meshforms"
fullnameOverride: "meshforms"

serviceAccount:
  create: false

podAnnotations:
  admission.datadoghq.com/js-lib.version: v5.22
podLabels:
  app: meshforms

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: forms.nycmesh.net
      paths:
        - path: /
          pathType: Prefix 
  tls: []

livenessProbe:
  httpGet:
    path: /en/
    port: http
readinessProbe:
  httpGet:
    path: /en/
    port: http

resources:
  limits:
    cpu: 1
    memory: 512Mi
  requests:
    cpu: 100m
    memory: 128Mi
