replicaCount: 3

image:
  repository: willnilges/meshforms
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "meshforms"
fullnameOverride: "meshforms"

serviceAccount:
  create: false

podAnnotations:
  admission.datadoghq.com/js-lib.version: v5.22
podLabels:
  app: meshforms

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  className: "traefik"
  annotations: {}
  hosts:
    - host: forms.mesh.nycmesh.net
      paths:
        - path: /
          pathType: Prefix 
  tls: []

livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

